[package]
name = "mix"
version = "0.1.1"
edition = "2021"
authors = ["aghil mohanads <a@xo.rs>"]
description = "markdown compiler with 🚀 fuel"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown-it = { version = "0.6.0", features = ["linkify", "syntect"] }
minimo = "0.3.19"
notify = "6.1.1"
pdf-writer = "0.9.2"
wkhtmltopdf = "0.4.0"
