[workspace]
members = [
    "platform",
    "draw",
    "widgets",
    "examples/hello_world",
    "examples/counter",
]

workspace.resolver = "2"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[profile.dev.package."*"]
opt-level = 3
