[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
mix-platform = { path = "../../platform" }
mix-draw = { path = "../../draw" }
mix-widgets = { path = "../../widgets" }
