[package]
name = "mix-draw"
version = "0.1.0"
edition = "2021"
description = "mix drawing layer"
license = "MIT OR Apache-2.0"

[dependencies]
mix-platform = { path = "../platform" }
ttf-parser = "0.25.1"
ab_glyph_rasterizer = "0.1.8"
unicode-segmentation = "1.11.0"
