[package]
name = "mix-widgets"
version = "0.1.0"
edition = "2021"
description = "mix widget system"
license = "MIT OR Apache-2.0"

[dependencies]
mix-platform = { path = "../platform" }
mix-draw = { path = "../draw" }
